### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by impressivewebs** [DataEasy/slack-hooker#16]
Hi, I got your tweet about this for my newsletter (http://webtoolsweekly.com/). It looks like this is some kind of Slack-based productivity tool, which is fine, I can include it.

But I have no idea what it is, specifically. And I can't tell from the README. Can you edit the README to include a one or two sentence description that makes sense to most people, to describe exactly what this is? Thanks!

**Comment by lfilho** [comment]
Sure, thing! This indeed is clearer to people already familiar to Slack and know what they're looking for, but you're right, I'll make a more common description.

Thanks

**Comment by lfilho** [comment]
There you go, @impressivewebs . See https://github.com/DataEasy/slack-hooker/commit/728ebe259eefe025f035bf2b7fe2638417766bcf and tell us if it's better now ;)

Thank you again

**Comment by impressivewebs** [comment]
Yep, that should be sufficient. Thanks!
